language: node_js
node_js:
  - '10'
script:
  - npm run generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: K+u4Cg8k9t8QVSWANUIUqSHHdgxH0SFk6ZeXyT0A3MApPvx69OClfN2ezUz4N5Hr/s23PXr3iH9si+kdXi0oVBH3i6rDNMXo8phbRgVOzF1A/OMZ3VFXRI/NaSl6S0roSaqdKvSUyv9G09IF6EURIeqA2GlhwS4ZJJr+YvzKCJlyLpL1wdXKcAr//ACn39awwtBIgyUXfMr0wEp4INuHTQYPq9/INXS8SnN0aRea1PCtQaNFuArVUqG3cjNbGxSohy02RuyEtvxgFkAZm++SYwznTs/gDENRZLf3qnosANPK3Y4Kr6M1iJgOcHQ/8gG0U0kQWA/Iog4WKtYDjlfCqjtxUHUxZ04A8Ug8Y/5/iWkKqLGMEC5Ko4i0KFzJPTu8FN9CkTlpOagbcqkDscO3zJ26eOtO+rrcV/ANvXy9D9Gl+CwiMHiSKV/lL3gI8K6EOdw76yT0Iz2yeCGjWc8FrpPvdXwXemJHnppaOlnG2UBRvGlAnQyWDLvtd5CgKJPcLl9Pcy8QWM95y30xGE7z+YX2ZzH5LOsUYXF/zRYfqQ+Zc/Dl3bKdbk6r6+R2Nxgoz2KyKz49dbt48UOEuvnJdFXWfbncBB1SfwyDb+QfKXkUOhKZxd78LiOnY2jBLm+/UvspdHx7v/LbIBF0HR652tza1i5bCmA9b8tPRLQM/OE=
  keep-history: true
  on:
    branch: modern
  local-dir: dist
  repo: AndreiStefanie/AndreiStefanie.github.io
