language: node_js
node_js:
  - '12'
script:
  - npm run generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: modern
  local-dir: dist
  repo: AndreiStefanie/AndreiStefanie.github.io
  target-branch: master
