language: node_js
node_js:
  - '10'
script:
  - npm run generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: 'TMOTrop3WwAzscjdfh8cZfSPXh1GNAv5tR/aWovDopSmVRYQjzgC7irsfYhqZ6Z/paCofCXG7X2+d8aP2CTUklqUpFLRW3A4GW/8Ptx3svyh6sxFFbYlamtrBlKIPOqKQpzH/9vfTtzM/OQg5lLNII4SbyZbJpAMJKtOVd9djZEpdiZnbbFrasskgPBEGdx0dxxPQ9T1JqFNYohzDmj9Rp+oj7VT2r16WVEAfid5NAko2/TG6z7lHH3Zv9WvT/ukQdXJlhFamZXhK1OaPbiE//vXsoWhNrCHhG4TR55IhVnVEzBteFXb6oXgbcQQ7HA2ONDAfDhpcDEU9NGwVj/m9dIeH0+W82Fue12ltnCFZlizkZ7+WV+noYMFr2P6+8Ca1TJKHl1fM+saFwRONa9u0a/pw50xoehjdCij1VF8vgzxVPwV6M5fOXXR/HLrlZGYQrsQpq4TS3BxsMoFmt19BAwgJRcDXe+gJeSaEw4Ep1yNsiPhGMcXr9/wPTJagMe16SzSV0Ka08K47gQ4UYjPynvx+sZxmz7HDSLWkR9xSZ49UWK0HdTEaUOYJ47qc9vf1X8OkFWy83TadphL40I+EcWiPeLf0X5CAgyluStOTQF6C0VD1VNquCVmHZQ66e/fRokX+nap12jEN9EU8Yem3/x0Nu8iiYravgSe0kyuxW4='
  keep-history: true
  on:
    branch: modern
  local-dir: dist
  repo: 'AndreiStefanie/AndreiStefanie.github.io'
